#!/bin/sh

[ -f 'index.html?p=xz-java.git;a=blob_plain;f=NEWS;hb=HEAD' ] &&  rm 'index.html?p=xz-java.git;a=blob_plain;f=NEWS;hb=HEAD'
wget 'http://git.tukaani.org/?p=xz-java.git;a=blob_plain;f=NEWS;hb=HEAD' >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	md5sum < 'index.html?p=xz-java.git;a=blob_plain;f=NEWS;hb=HEAD' > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'xz-java'
	fi
	rm 'index.html?p=xz-java.git;a=blob_plain;f=NEWS;hb=HEAD'
elif [ ! -f unfetchable ]
	touch unfetchable
	echo 'xz-java (unfetchable)'
fi

