#!/bin/sh

[ -f 'NEWS.text' ] &&  rm 'NEWS.text'
wget 'http://www.pps.univ-paris-diderot.fr/~jch/software/cedilla/NEWS.text' >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	md5sum < NEWS.text > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'cedilla'
	fi
	rm NEWS.text
elif [ ! -f unfetchable ]
	touch unfetchable
	echo 'cedilla (unfetchable)'
fi

