#!/bin/sh

[ -f 'pony' ] &&  rm 'pony'
wget http://hackage.haskell.org/package/pony >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	md5sum < pony > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'pony'
	fi
	rm pony
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'pony (unfetchable)'
fi

