#!/bin/sh

[ -f prolog.el ] &&  rm prolog.el

wget 'http://bruda.ca/_media/emacs/prolog.el' -O prolog.el >/dev/null 2>/dev/null

if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	md5sum prolog > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'emacs-prolog-mode'
	fi
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'emacs-prolog-mode (unfetchable)'
fi

