#!/bin/sh

[ -f 'index.html' ] &&  rm 'index.html'
wget http://sourceforge.net/projects/qtsixa/files/ >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	grep 'title="QtSixA' < index.html | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'qtsixa'
	fi
	rm index.html
elif [ ! -f unfetchable ]
	touch unfetchable
	echo 'qtsixa (unfetchable)'
fi

