#!/bin/sh

wget http://sourceforge.net/projects/qtsixa/files/ >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	grep QtSixA < index.html | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'qtsixa'
	fi
	rm index.html
else
	echo 'qtsixa (unfetchable)'
fi

