#!/bin/sh

[ -f paredit.release ] &&  rm paredit.release

wget 'http://mumble.net/~campbell/emacs/paredit.release' -O paredit.release >/dev/null 2>/dev/null

if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	md5sum paredit.release > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'paredit'
	fi
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'paredit (unfetchable)'
fi

