#!/bin/sh

wget http://code.google.com/p/javagnutar/ >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	grep \\.zip < index.html | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'javagnutar'
	fi
	rm index.html
elif [ ! -f unfetchable ]
	touch unfetchable
	echo 'javagnutar (unfetchable)'
fi

