#!/bin/sh

[ -f 'versions' ] &&  rm 'versions'
wget http://henning.makholm.net/xcftools -O - | grep -Po '<a [^>]*>' | grep 'xcftools' | grep -v asc > versions
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	md5sum < versions > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'xcftools'
	fi
	rm versions
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'xcftools (unfetchable)'
fi

