#!/bin/sh

[ -f 'index.html' ] &&  rm 'index.html'
wget http://spot-on.sourceforge.net/ >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	grep 'has been released' < index.html | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'dooble'
	fi
	rm index.html
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'dooble (unfetchable)'
fi

