#!/bin/sh

[ -f 'plugins.php?branch=EXT' ] &&  rm 'plugins.php?branch=EXT'
wget 'http://www.claws-mail.org/plugins.php?branch=EXT' >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
        head --lines=$(( $(grep -n RSSyl < 'plugins.php?branch=EXT' | cut -f 1 -d \:) + 30 )) < 'plugins.php?branch=EXT' | tail --lines=30 | grep nowrap | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'rssyl'
	fi
	rm 'plugins.php?branch=EXT'
elif [ ! -f unfetchable ]
	touch unfetchable
	echo 'rssyl (unfetchable)'
fi

