#!/bin/sh

[ -f 'files' ] &&  rm 'files'
wget http://sourceforge.net/projects/xtux/files >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	grep 'Download xtux-src-' < files | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'xtux'
	fi
	rm files
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'xtux (unfetchable)'
fi

