#!/bin/sh

wget http://www.scala-lang.org/downloads -O - 2>/dev/null | grep -Po 'scala-tool-support-.+>' | head -n 2 > release

if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	md5sum release > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'emacs-scala-mode'
	fi
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'emacs-scala-mode (unfetchable)'
fi

