#!/bin/sh

[ -f 'releases' ] &&  rm 'releases'
wget https://github.com/christianbundy/sshcd/releases -O releases >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	[ -f unfetchable ] && rm unfetchable
	grep '</span> Tags' < releases | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'latex-beamer'
	fi
	rm releases
elif [ ! -f unfetchable ]; then
	touch unfetchable
	echo 'latex-beamer (unfetchable)'
fi

