#!/bin/sh

wget http://code.google.com/p/vectex/ >/dev/null 2>/dev/null
if [ $? = 0 ]; then
	grep release < index.html | md5sum > new-sum
	touch sum
	if [ "$(cat sum)" = "$(cat new-sum)" ]; then
		rm new-sum
	else
		mv new-sum sum
		echo 'blender-plugin-vectex'
	fi
	rm index.html
else
	echo 'blender-plugin-vectex (unfetchable)'
fi

